apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-kv-provider
  namespace: argocd
spec:
  provider: azure
  secretObjects:
    - secretName: mysql-db-password
      type: Opaque
      data:
        - objectName: db-password
          key: db-password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 2ad2ca06-184f-49f3-9f8a-232af2eb1dbc
    keyvaultName: my-keyvault-rg9
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: 7228ccd0-4940-47c3-8fc6-ac0294a7a2a0