apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp2-service
  namespace: argocd
  labels: 
    app: usermgmt-webapp2
spec: 
  type: LoadBalancer
  selector: 
    app: usermgmt-webapp2
  ports: 
    - port: 80
      targetPort: 8080